on:
  workflow_dispatch:
    inputs:
      ip:
        required: true
        default: '0.0.0.0'
        type: string

jobs:
  job:
    uses: mirllan2025/express/.github/workflows/ci.yml@master
    with:
      ip: ${{inputs.ip}}
